version: 1
formatters:
  default:
    format: "[%(asctime)s] [%(levelname)s] [%(process)d] [%(name)s] [%(filename)s:%(lineno)d] [%(funcName)s] %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
root:
  level: INFO
  handlers: [console]
