version: "3"

services:
  postgres:
    image: postgres:13.5
    container_name: postgres
    restart: always
    networks:
      - default
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=row_level_security_with_python
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
    hostname: postgres
    stdin_open: true

  api:
    container_name: api
    image: shibui/row_level_security_with_python:0.1.0
    restart: always
    networks:
      - default
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=row_level_security_with_python
      - WORKERS=1
      - PORT=8000
    command: >
      /bin/sh -c "./run.sh"
    hostname: api
    depends_on:
      - postgres

  job:
    container_name: job
    image: shibui/row_level_security_with_python:0.1.0
    restart: always
    networks:
      - default
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=row_level_security_with_python
    command: python -m src.batch
    hostname: job
    depends_on:
      - postgres


networks:
  default:
    name: row_level_security_with_python
